### ISSUE TITLE
[5th 10PP] Finsih final fabrication

### ISSUE THREAD

**Issue by rocco8773** [GAPS-Collab/Tasks#145]
- [x] Process 80 paddle spacers
- [x] Process Top Straps
- [x] Epoxy inserts
- [x] Epoxy corners
- [x] Epoxy paddle spacers to foam board
- [x] Epoxy paddle spacers to Top Straps

---

- Inserts were epoxied WITH the G10/FR4 spacers, except for the two sets of countersink inserts (used for the Top Straps) at the bottom A-side of the panel

**Comment by rocco8773** [comment]
7 Mar. 2023

- Everything is epoxied
- Hardware has been removed
- Everything has been cleaned and prepped for strapping.
