### ISSUE TITLE
[4th 10PP] Finish final fabrication

### ISSUE THREAD

**Issue by rocco8773** [GAPS-Collab/Tasks#146]
- [x] Process 80 paddle spacers
- [x] Process Top Straps
- [x] Epoxy inserts
- [x] Epoxy corners
- [x] Epoxy paddle spacers to foam board
- [x] Epoxy paddle spacers to Top Straps

---

- Inserts were epoxied WITH the G10/FR4 spacers
- Refer to #20 for explanation of the G10/FR4 spacers.

**Comment by rocco8773** [comment]
7 Mar. 2023

- Everything is epoxied
- Hardware has been removed, except for a few snapped screws
- Snapped screws need to be removed from top straps
- Panel and Top Straps need to be cleaned
