### ISSUE TITLE
Pre-Palestine To-Do List

### ISSUE THREAD

**Issue by rocco8773** [GAPS-Collab/Tasks#209]
- [ ] Update PCB in RATs 1-6
- [ ] Remove broken screw from RAT 9 baseplate
- [ ] install edge paddle adapter bracket TKR-631
- [ ] install TKR vertical attachment block TKR-642
- [ ] install updated upper radiator mounts
