### ISSUE TITLE
[2nd 06PP] Finish final fabrication

### ISSUE THREAD

**Issue by rocco8773** [GAPS-Collab/Tasks#29]
Finish fabrication of 06PP

- [x] #31 
- [x] #51 
- [x] Sand foam panel for inserts
- [x] Sand foam panel corners
- [x] #32
- [x] #33 (can still be done after strapping)
- [x] #54
- [x] #57

**Comment by rocco8773** [comment]
Since this panel has the wrong inserts epoxied into one mounting location https://github.com/rocco8773/gaps_work/issues/32#issuecomment-1273629630, I want to pause ⏸ epoxying of paddles spacers to the foam board.  This panel should be the one of the last 06PPs to be epoxied.
