### ISSUE TITLE
[3rd 06PP] Finish final fabrication

### ISSUE THREAD

**Issue by rocco8773** [GAPS-Collab/Tasks#30]
Finish fabrication of 06PP

- [x] #35
- [x] #52
- [x] Sand foam panel for inserts
- [x] Sand foam panel corners
- [x] #36
- [x] #34 (can still be done after strapping)
- [x] #55 
- [x] #58
