### ISSUE TITLE
[4th 12PP] Finish final fabrication

### ISSUE THREAD

**Issue by rocco8773** [GAPS-Collab/Tasks#66]
- [x] Process 96 paddle spacers
- [x] Process Top Straps
- [x] Epoxy inserts
- [x] Epoxy corners
- [x] Epoxy paddle spacers to foam board
- [x] Epoxy paddle spacers to Top Straps

**Comment by rocco8773** [comment]
Finished 3 Feb. 2023
